/**
* XBOX 
* buttons are either 0 or 1
* button axes go from 0 to -1
* stick axes go from 0 to +/-1
**/

#define XBOX_BUTTON_A 0
#define XBOX_BUTTON_B 1
#define XBOX_BUTTON_X 2
#define XBOX_BUTTON_Y 3
#define XBOX_BUTTON_LB 4
#define XBOX_BUTTON_RB 5
#define XBOX_BUTTON_BACK 6
#define XBOX_BUTTON_START 7
#define XBOX_BUTTON_POWER 8
#define XBOX_BUTTON_STICK_LEFT 9
#define XBOX_BUTTON_STICK_RIGHT 10
#define XBOX_BUTTON_CROSS_LEFT 11
#define XBOX_BUTTON_CROSS_RIGHT 12
#define XBOX_BUTTON_CROSS_UP 13
#define XBOX_BUTTON_CROSS_DOWN 14

#define XBOX_AXIS_LEFT_RIGHT_STICK_LEFT 0
#define XBOX_AXIS_UP_DOWN_STICK_LEFT 1
#define XBOX_AXIS_LT 2
#define XBOX_AXIS_LEFT_RIGHT_STICK_RIGHT 3
#define XBOX_AXIS_UP_DOWN_STICK_RIGHT 4
#define XBOX_AXIS_RT 5
