global_costmap:
  global_frame: map
  static_map: true

local_costmap:
  global_frame: r2/odom
  static_map: false
  rolling_window: true
  width: 2.0
  origin_x: -1.0
  origin_y: 0.0
  resolution: 0.01 # meters/cell