# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
mobile_base_controller:
  type        : diff_drive_controller/DiffDriveController
  left_wheel  : 'left_wheel_to_base'
  right_wheel : 'right_wheel_to_base'
  publish_rate: 25.0               # default: 50
  publish_cmd: true
  enable_odom_tf: true            # TF is publihed by the ukf filter
  open_loop: false
  
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.190
  wheel_radius : 0.0375

  # Wheel separation and radius multipliers
  # (JB : Calculated using rqt_reconfigure and some tests on the ground with teleop)
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.02 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: 'r2/base_link' #default: base_link
  odom_frame_id: 'r2/odom'

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.27  # m/s
      min_velocity           : -0.27 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # m/s^2
      min_acceleration       : -0.5 # m/s^2
      has_jerk_limits        : false
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.8  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 4.0  # rad/s^2
      has_jerk_limits        : false